spring:
  application:
    name: notification-service
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      eureka:
        client:
          service-url:
            defaultZone: http://localhost:8761/eureka/
        instance:
          prefer-ip-address: true
          hostname: localhost
  mail:
    host: localhost
    port: ${greenmail.smtp.port:3025}
    username: test
    password: test
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
      mail.debug: true

server:
  port: 8086

logging:
  level:
    org.springframework.kafka: DEBUG